#  Copyright 2026 Ram Narayanan
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0

"""
code_integrator.py — Code Generation Agent: Integrator stage.

Fan-in stage. Reads plan and all component code content from TitanStore,
calls Gemini to merge them into a single cohesive Python file, writes the
output locally, uploads it to the master, and stores the filename in TitanStore
for the orchestrator to fetch.

Args: <run_id> <goal_with_underscores>

Requires: pip install google-genai python-dotenv
"""

import sys
import os
import json
from dotenv import load_dotenv

load_dotenv()


def main():
    if len(sys.argv) < 3:
        print("Usage: code_integrator.py <run_id> <goal>", flush=True)
        sys.exit(1)

    run_id = sys.argv[1]
    goal   = " ".join(sys.argv[2:]).replace("_", " ")

    print("=" * 60, flush=True)
    print(f"[INTEGRATOR] Goal  : {goal}", flush=True)
    print(f"[INTEGRATOR] Run ID: {run_id}", flush=True)
    print("=" * 60, flush=True)

    from titan_sdk import TitanClient
    tc = TitanClient()

    # Read plan from TitanStore
    plan_json = tc.store_get(f"code:{run_id}:plan")
    if not plan_json or plan_json in ("NULL", "CLEARED"):
        print(f"[ERROR] Plan not found in TitanStore.", flush=True)
        sys.exit(1)

    plan = json.loads(plan_json)
    components = sorted(plan["components"], key=lambda c: c["idx"])

    # Read each component's latest code content from TitanStore
    # (fixer overwrites the same key, so this always gets the final version)
    code_blocks = []
    for c in components:
        content = tc.store_get(f"code:{run_id}:component:{c['idx']}:content")
        if not content or content in ("NULL", "CLEARED"):
            print(f"[INTEGRATOR]   No content for component {c['idx']} — skipping", flush=True)
            continue
        code_blocks.append((c["idx"], c["name"], content))
        print(f"[INTEGRATOR]   {c['name']} — {len(content)} chars  ✓", flush=True)

    if not code_blocks:
        print("[ERROR] No component content found in TitanStore.", flush=True)
        sys.exit(1)

    api_key = os.environ.get("GEMINI_API_KEY", "")
    if not api_key:
        print("[ERROR] GEMINI_API_KEY not set.", flush=True)
        sys.exit(1)

    from google import genai
    from google.genai import types

    components_block = "\n\n---\n\n".join(
        f"### {name}\n```python\n{code}\n```"
        for _, name, code in code_blocks
    )

    prompt = f"""You are an expert Python developer integrating multiple modules into one cohesive program.

Goal: "{goal}"

Individual components (already reviewed and approved):
{components_block}

Integrate all components into a single, well-structured Python file that:
1. Keeps each component as a clearly separated section with a comment header
2. Resolves any import conflicts or naming collisions
3. Adds a main() function that demonstrates the system working end-to-end
4. Includes an if __name__ == "__main__": block that calls main()
5. Adds a module-level docstring describing the complete system

The result should be a working, runnable Python program.
Return ONLY the Python code, no markdown fences, no explanation."""

    print(f"\n[INTEGRATOR] Calling Gemini to integrate components...", flush=True)

    client   = genai.Client(api_key=api_key)
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt,
        config=types.GenerateContentConfig(temperature=0.2)
    )

    integrated = response.text.strip()
    if integrated.startswith("```"):
        lines = integrated.split("\n")
        integrated = "\n".join(lines[1:-1] if lines[-1].strip() == "```" else lines[1:])

    # Write final file locally (worker CWD = titan_workspace/shared)
    out_filename = f"code_{run_id}_final.py"
    with open(out_filename, "w") as f:
        f.write(f'"""\nGenerated by Titan Code Generation Agent\nGoal: {goal}\nRun ID: {run_id}\nComponents: {", ".join(c["name"] for c in components)}\n"""\n\n')
        f.write(integrated)

    print(f"[INTEGRATOR] Final code written locally ({len(integrated)} chars)", flush=True)

    # Publish final file to master — orchestrator retrieves via get_artifact
    try:
        tc.publish_artifact(f"code:{run_id}:final", out_filename)
        tc.store_put(f"code:{run_id}:integrator:done", "1")
        print(f"[INTEGRATOR] Final file published to master.", flush=True)
    except Exception as e:
        print(f"[INTEGRATOR] TitanStore/upload skipped: {e}", flush=True)

    print(f"\n--- Preview (first 20 lines) ---", flush=True)
    for line in integrated.split("\n")[:20]:
        print(line, flush=True)
    print("...\n", flush=True)


if __name__ == "__main__":
    main()
