"""
Generated by Titan Code Generation Agent
Goal: Build a Python CLI task manager with priority queuing and JSON persistence
Run ID: 850e53b3c5fa
Components: task_core, task_persistence, cli_interface
"""

"""
A command-line task manager with priority queuing and JSON persistence.

This program integrates three core components:
1.  **task_core**: Manages the in-memory representation and logic of tasks,
    including adding, removing, listing, updating priority, and marking complete.
    It uses a `Task` dataclass and a `TaskCore` manager class.
2.  **task_persistence**: Handles reading and writing task data to/from a JSON file.
    It serializes/deserializes lists of task dictionaries.
3.  **cli_interface**: Provides the command-line argument parsing, user interaction,
    and orchestrates calls between `task_core` and `task_persistence`.

The system allows users to manage tasks with descriptions, priorities (1-5),
and completion status, persisting them to a JSON file for continuity.
"""

import argparse
import os
import sys
import json
import itertools
from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any


# --- Component: task_core ---
# Generated: iteration 1

class TaskNotFoundError(ValueError):
    """Raised when a task with the given ID is not found."""
    pass

@dataclass
class Task:
    """
    Represents a single task with its ID, description, priority, and completion status.
    """
    id: int
    description: str
    priority: int
    completed: bool = False

    def to_dict(self) -> Dict[str, Any]:
        """
        Converts the Task object to a dictionary, suitable for serialization
        (e.g., to JSON by the task_persistence module).
        """
        return {
            "id": self.id,
            "description": self.description,
            "priority": self.priority,
            "completed": self.completed,
        }

    @staticmethod
    def from_dict(data: Dict[str, Any]) -> 'Task':
        """
        Creates a Task object from a dictionary, typically loaded from
        deserialized data (e.g., from JSON by the task_persistence module).
        """
        # Ensure all required fields are present, provide defaults for optional ones
        return Task(
            id=data["id"],
            description=data["description"],
            priority=data["priority"],
            completed=data.get("completed", False) # Default to False if 'completed' is missing
        )


class TaskCore:
    """
    Manages the in-memory collection of tasks and provides core logic for
    task manipulation.
    """
    _next_id_counter: itertools.count
    _tasks: Dict[int, Task] # Stores tasks by ID for O(1) lookup

    def __init__(self):
        """
        Initializes the TaskCore with an empty task collection and an ID counter.
        The ID counter starts from 1 by default.
        """
        self._next_id_counter = itertools.count(1)
        self._tasks = {}

    def _get_next_id(self) -> int:
        """
        Generates a unique, sequential ID for a new task.
        """
        return next(self._next_id_counter)

    def initialize_tasks_from_data(self, task_dicts: List[Dict[str, Any]]) -> None:
        """
        Initializes the task manager with a list of task dictionaries.
        This method is typically called once after TaskCore instantiation
        to load existing data from persistence.

        It clears any existing in-memory tasks and rebuilds the collection
        from the provided data, ensuring the ID counter resumes correctly.

        Args:
            task_dicts: A list of dictionaries, each representing a task.
        """
        self._tasks.clear() # Clear any existing tasks before loading new ones
        max_id = 0
        for task_dict in task_dicts:
            task = Task.from_dict(task_dict)
            self._tasks[task.id] = task
            if task.id > max_id:
                max_id = task.id
        # Set the ID counter to continue from the largest existing ID + 1
        # This prevents ID collisions when adding new tasks after loading.
        self._next_id_counter = itertools.count(max_id + 1)

    def add_task(self, description: str, priority: int) -> Task:
        """
        Adds a new task to the manager.

        Args:
            description: A string describing the task.
            priority: An integer indicating the task's priority (lower number = higher priority).

        Returns:
            The newly created Task object.
        """
        task_id = self._get_next_id()
        new_task = Task(id=task_id, description=description, priority=priority)
        self._tasks[task_id] = new_task
        return new_task

    def remove_task(self, task_id: int) -> None:
        """
        Removes a task by its ID.

        Args:
            task_id: The unique identifier of the task to remove.

        Raises:
            TaskNotFoundError: If no task with the given ID exists.
        """
        if task_id not in self._tasks:
            raise TaskNotFoundError(f"Task with ID {task_id} not found.")
        del self._tasks[task_id]

    def get_tasks(self, sorted_by_priority: bool = True) -> List[Task]:
        """
        Retrieves all tasks, optionally sorted by priority.

        Args:
            sorted_by_priority: If True, tasks are sorted first by priority (ascending,
                                 meaning lower number is higher priority) and then
                                 by ID (ascending) for stable sorting.

        Returns:
            A list of Task objects.
        """
        tasks_list = list(self._tasks.values())
        if sorted_by_priority:
            # Sort by priority (ascending), then by ID (ascending) for stable order
            tasks_list.sort(key=lambda task: (task.priority, task.id))
        return tasks_list

    def update_task_priority(self, task_id: int, new_priority: int) -> None:
        """
        Updates the priority of an existing task.

        Args:
            task_id: The unique identifier of the task to update.
            new_priority: The new priority value for the task.

        Raises:
            TaskNotFoundError: If no task with the given ID exists.
        """
        if task_id not in self._tasks:
            raise TaskNotFoundError(f"Task with ID {task_id} not found.")
        self._tasks[task_id].priority = new_priority

    def mark_task_complete(self, task_id: int) -> None:
        """
        Marks a task as complete.

        Args:
            task_id: The unique identifier of the task to mark complete.

        Raises:
            TaskNotFoundError: If no task with the given ID exists.
        """
        if task_id not in self._tasks:
            raise TaskNotFoundError(f"Task with ID {task_id} not found.")
        self._tasks[task_id].completed = True

    def get_all_tasks_as_dicts(self) -> List[Dict[str, Any]]:
        """
        Exports all current tasks as a list of dictionaries.
        This format is suitable for persistence (e.g., saving to JSON
        by the task_persistence module).

        Returns:
            A list of dictionaries, each representing a task.
        """
        return [task.to_dict() for task in self._tasks.values()]


# --- Component: task_persistence ---
# Generated: iteration 1

"""
This module handles the serialization and deserialization of task data to and from a JSON file.

It provides functions to load a list of task dictionaries from a specified file
and to save a list of task dictionaries to a specified file.
"""

# Define a type alias for a task dictionary for better readability
TaskDict = Dict[str, Any]


def load_tasks(filepath: str) -> List[TaskDict]:
    """
    Loads a list of task dictionaries from a JSON file.

    If the file does not exist or is empty/malformed, an empty list is returned.

    Args:
        filepath (str): The path to the JSON file where tasks are stored.

    Returns:
        List[TaskDict]: A list of dictionaries, where each dictionary represents a task.
                        Returns an empty list if the file is not found or is invalid.
    """
    if not os.path.exists(filepath):
        # If the file doesn't exist, it means no tasks have been saved yet.
        # Return an empty list to indicate an empty task list.
        return []

    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            # Attempt to load JSON data from the file.
            tasks = json.load(f)
            # Ensure the loaded data is indeed a list. If the file contains
            # something else (e.g., a single dict), treat it as invalid.
            if not isinstance(tasks, list):
                print(f"Warning: Data in '{filepath}' is not a list. Returning empty list.")
                return []
            return tasks
    except json.JSONDecodeError:
        # Catch errors if the file content is not valid JSON.
        print(f"Error: Could not decode JSON from '{filepath}'. File might be corrupted. Returning empty list.")
        return []
    except IOError as e:
        # Catch other potential I/O errors (e.g., permission denied).
        print(f"Error reading file '{filepath}': {e}. Returning empty list.")
        return []


def save_tasks(tasks: List[TaskDict], filepath: str) -> None:
    """
    Saves a list of task dictionaries to a JSON file.

    The data is saved with an indent of 4 spaces for human readability.

    Args:
        tasks (List[TaskDict]): A list of dictionaries, where each dictionary represents a task.
        filepath (str): The path to the JSON file where tasks will be saved.
    """
    try:
        # Ensure the directory for the filepath exists.
        # This prevents FileNotFoundError if the directory structure isn't in place.
        os.makedirs(os.path.dirname(filepath), exist_ok=True)

        with open(filepath, 'w', encoding='utf-8') as f:
            # Use json.dump to write the list of task dictionaries to the file.
            # indent=4 makes the JSON output pretty-printed, which is useful for debugging.
            json.dump(tasks, f, indent=4, ensure_ascii=False)
    except IOError as e:
        # Catch potential I/O errors during writing (e.g., permission denied, disk full).
        print(f"Error writing to file '{filepath}': {e}")


# --- Component: cli_interface ---
# Fixed: review_iteration 2, issue 2
# Fixed: review_iteration 1, issue 1
# Generated: iteration 1

"""
cli_interface.py

Provides the command-line interface for user interaction with the task manager.
It parses command-line arguments, translates user commands into calls to the
task_core module, formats the output for display, and triggers persistence
operations via the task_persistence module.
"""

# --- Configuration Constants ---
DEFAULT_DB_FILE = os.path.expanduser("~/.task_manager.json")


def _setup_argument_parser() -> argparse.ArgumentParser:
    """
    Sets up the argparse parser for the CLI.
    """
    parser = argparse.ArgumentParser(
        description="A command-line task manager with priority queuing."
    )
    parser.add_argument(
        "--db",
        default=DEFAULT_DB_FILE,
        help=f"Specify the database file (default: {DEFAULT_DB_FILE})",
    )

    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # Add command
    add_parser = subparsers.add_parser(
        "add", help="Add a new task to the list."
    )
    add_parser.add_argument(
        "description", type=str, help="Description of the task."
    )
    add_parser.add_argument(
        "-p",
        "--priority",
        type=int,
        default=1,
        choices=range(1, 6),
        metavar="[1-5]",
        help="Priority of the task (1=highest, 5=lowest, default: 1).",
    )

    # List command
    list_parser = subparsers.add_parser(
        "list", help="List all active tasks by priority."
    )
    list_parser.add_argument(
        "-a",
        "--all",
        action="store_true",
        help="Show all tasks, including completed ones.",
    )

    # Remove command
    remove_parser = subparsers.add_parser(
        "remove", help="Remove a task by its ID."
    )
    remove_parser.add_argument(
        "task_id", type=int, help="The ID of the task to remove."
    )

    # Update priority command
    update_parser = subparsers.add_parser(
        "update", help="Update the priority of an existing task."
    )
    update_parser.add_argument(
        "task_id", type=int, help="The ID of the task to update."
    )
    update_parser.add_argument(
        "new_priority",
        type=int,
        choices=range(1, 6),
        metavar="[1-5]",
        help="The new priority for the task (1=highest, 5=lowest).",
    )

    # Mark complete command
    complete_parser = subparsers.add_parser(
        "complete", help="Mark a task as completed."
    )
    complete_parser.add_argument(
        "task_id", type=int, help="The ID of the task to mark as complete."
    )

    return parser


def _display_tasks(tasks: List[Task], include_completed: bool = False) -> None:
    """
    Formats and prints the list of tasks to the console.
    """
    if not tasks:
        print("No tasks found.")
        return

    print(f"\n{'ID':<4} {'P':<2} {'Status':<10} {'Description':<50}")
    print(f"{'-'*4:<4} {'-'*2:<2} {'-'*10:<10} {'-'*50:<50}")

    for task in tasks:
        if not include_completed and task.completed:
            continue  # Skip completed tasks if not requested

        task_id = task.id
        priority = task.priority
        description = task.description
        status = "COMPLETE" if task.completed else "ACTIVE"
        print(f"{task_id:<4} {priority:<2} {status:<10} {description:<50}")
    print("\n")


def run_cli() -> None:
    """
    The main entry point for the command-line interface.
    It orchestrates argument parsing, interaction with TaskCore,
    and persistence operations.
    """
    parser = _setup_argument_parser()
    args = parser.parse_args()

    # Initialize the TaskCore manager
    task_manager = TaskCore()

    # Load tasks from persistence at startup
    try:
        loaded_tasks_data = load_tasks(args.db)
        task_manager.initialize_tasks_from_data(loaded_tasks_data)
    except FileNotFoundError:
        print(f"No task database found at '{args.db}'. Starting with an empty list.")
    except Exception as e:
        print(f"Error loading tasks from '{args.db}': {e}")
        sys.exit(1)

    # Flag to determine if tasks were modified and need saving
    tasks_modified = False

    # Handle commands
    if args.command == "add":
        try:
            new_task = task_manager.add_task(args.description, args.priority)
            print(f"Task added: ID {new_task.id}, Priority {new_task.priority} - '{new_task.description}'")
            tasks_modified = True
        except ValueError as e:
            print(f"Error adding task: {e}")
            sys.exit(1)
    elif args.command == "list":
        # Get tasks from TaskCore, sorted by priority by default
        tasks_to_display = task_manager.get_tasks(
            sorted_by_priority=True
        )
        _display_tasks(tasks_to_display, include_completed=args.all)
    elif args.command == "remove":
        try:
            task_manager.remove_task(args.task_id)
            print(f"Task ID {args.task_id} removed successfully.")
            tasks_modified = True
        except TaskNotFoundError:
            print(f"Error: Task with ID {args.task_id} not found.")
            sys.exit(1)
        except Exception as e:
            print(f"Error removing task: {e}")
            sys.exit(1)
    elif args.command == "update":
        try:
            task_manager.update_task_priority(args.task_id, args.new_priority)
            print(f"Task ID {args.task_id} priority updated to {args.new_priority}.")
            tasks_modified = True
        except TaskNotFoundError:
            print(f"Error: Task with ID {args.task_id} not found.")
            sys.exit(1)
        except ValueError as e:
            print(f"Error updating task priority: {e}")
            sys.exit(1)
        except Exception as e:
            print(f"Error updating task: {e}")
            sys.exit(1)
    elif args.command == "complete":
        try:
            task_manager.mark_task_complete(args.task_id)
            print(f"Task ID {args.task_id} marked as complete.")
            tasks_modified = True
        except TaskNotFoundError:
            print(f"Error: Task with ID {args.task_id} not found.")
            sys.exit(1)
        except ValueError as e:
            print(f"Error marking task complete: {e}")
            sys.exit(1)
        except Exception as e:
            print(f"Error completing task: {e}")
            sys.exit(1)
    else:
        # If no command is given, print help
        parser.print_help()
        sys.exit(0)

    # Save tasks back to persistence if any modifications were made
    if tasks_modified:
        try:
            # Get all tasks in a serializable format from the core manager
            all_tasks_for_persistence = task_manager.get_all_tasks_as_dicts()
            save_tasks(all_tasks_for_persistence, args.db)
        except Exception as e:
            print(f"Error saving tasks to '{args.db}': {e}")
            sys.exit(1)


def main() -> None:
    """
    Main entry point for the integrated CLI task manager.
    """
    run_cli()


if __name__ == "__main__":
    main()