#  Copyright 2026 Ram Narayanan
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0

"""
comp_intel_synthesizer.py — Titan worker for the Competitive Intelligence Pipeline.

Fan-in synthesis stage. Reads all analyst result files from the shared workspace,
calls Gemini to synthesize a final comparison report, and saves it as Markdown.

Args: <run_id> <count> <framework_0> <framework_1> ... <framework_N>

Requires:
    pip install google-genai python-dotenv
"""

import sys
import os
from dotenv import load_dotenv

load_dotenv()


def main():
    if len(sys.argv) < 4:
        print("Usage: comp_intel_synthesizer.py <run_id> <count> <fw0> <fw1> ...", flush=True)
        sys.exit(1)

    run_id     = sys.argv[1]
    count      = int(sys.argv[2])
    frameworks = [fw.replace("_", " ") for fw in sys.argv[3:3 + count]]

    print("=" * 60, flush=True)
    print(f"[SYNTHESIS] Starting synthesis", flush=True)
    print(f"[SYNTHESIS] Frameworks : {', '.join(frameworks)}", flush=True)
    print(f"[SYNTHESIS] Run ID     : {run_id}", flush=True)
    print("=" * 60, flush=True)

    # Read analyst results from shared workspace files
    shared_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "shared")
    sections   = []
    missing    = []

    for i in range(count):
        result_file = os.path.join(shared_dir, f"intel_{run_id}_result_{i}.txt")
        if os.path.exists(result_file):
            with open(result_file, "r") as f:
                content = f.read()
            # First line is FRAMEWORK:<name>, rest is the analysis
            lines     = content.split("\n", 1)
            fw_name   = lines[0].replace("FRAMEWORK:", "").strip() if lines else frameworks[i]
            analysis  = lines[1].strip() if len(lines) > 1 else content
            sections.append((fw_name, analysis))
            print(f"[SYNTHESIS]   [{i}] {fw_name} — {len(analysis)} chars  ✓", flush=True)
        else:
            missing.append(i)
            print(f"[SYNTHESIS]   [{i}] {frameworks[i]} — file not found  ✗", flush=True)

    if not sections:
        print("[ERROR] No analyst results found. Cannot synthesize.", flush=True)
        sys.exit(1)

    if missing:
        print(f"[WARN] {len(missing)} result(s) missing — synthesizing with available data.", flush=True)

    api_key = os.environ.get("GEMINI_API_KEY", "")
    if not api_key:
        print("[ERROR] GEMINI_API_KEY not set.", flush=True)
        sys.exit(1)

    try:
        from google import genai
        from google.genai import types
    except ImportError:
        print("[ERROR] google-genai not installed.", flush=True)
        sys.exit(1)

    framework_names = ", ".join(name for name, _ in sections)
    research_block  = "\n\n---\n\n".join(
        f"## {name}\n\n{text}" for name, text in sections
    )

    col_headers = " | ".join(name for name, _ in sections)
    col_seps    = "|".join("---" for _ in sections)

    prompt = f"""You are a principal technology strategist. Your analysts have produced competitive briefs on: {framework_names}.

ANALYST REPORTS:

{research_block}

---

Synthesize into a decision-maker-ready comparison with this structure:

# Competitive Intelligence Report

## Executive Summary
(3 sentences. The single most important insight for a decision-maker choosing between these.)

## Head-to-Head Comparison

| Dimension | {col_headers} |
|---|{col_seps}|
| Primary use case | ... |
| Execution model | ... |
| Scalability | ... |
| Human oversight | ... |
| Setup complexity | ... |
| Best for teams that... | ... |

## Key Differentiators
(One paragraph per framework explaining its unique value and who should choose it.)

## Recommendation Matrix
("Choose X if..." for each framework — short, opinionated, specific.)

Be direct. A reader should be able to choose a framework after reading this."""

    print(f"\n[SYNTHESIS] Calling Gemini for final synthesis...", flush=True)

    client = genai.Client(api_key=api_key)
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt,
        config=types.GenerateContentConfig(temperature=0.2)
    )

    report = response.text.strip()

    # Save final report to shared workspace
    safe_fws = "_vs_".join(name.replace(" ", "-") for name, _ in sections)[:50]
    filename = os.path.join(shared_dir, f"comp_intel_{safe_fws}_{run_id[:8]}.md")

    with open(filename, "w") as f:
        f.write(f"# Competitive Intelligence: {framework_names}\n\n")
        f.write(f"*Generated by Titan · Run ID: `{run_id}`*\n\n---\n\n")
        f.write(report)
        f.write(f"\n\n---\n\n*Frameworks analysed: {framework_names}*\n")

    print(f"[SYNTHESIS] Report saved → {os.path.basename(filename)}", flush=True)
    print(f"\n{'=' * 60}", flush=True)
    for line in report.split("\n"):
        print(line, flush=True)
    print(f"{'=' * 60}\n", flush=True)


if __name__ == "__main__":
    main()
