#  Copyright 2026 Ram Narayanan
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0

"""
research_synthesizer.py — Agentic Research Agent: Synthesis stage.

Fan-in stage. Fetches all research result files from the master, calls Gemini
to synthesize a final polished report, writes the report locally, uploads it
to the master, and stores the filename in TitanStore for the orchestrator.

Args: <run_id> <query_with_underscores>

Requires: pip install google-genai python-dotenv
"""

import sys
import os
from dotenv import load_dotenv

load_dotenv()


def main():
    if len(sys.argv) < 3:
        print("Usage: research_synthesizer.py <run_id> <query>", flush=True)
        sys.exit(1)

    run_id = sys.argv[1]
    query  = " ".join(sys.argv[2:]).replace("_", " ")

    print("=" * 60, flush=True)
    print(f"[SYNTHESIS] Query  : {query}", flush=True)
    print(f"[SYNTHESIS] Run ID : {run_id}", flush=True)
    print("=" * 60, flush=True)

    from titan_sdk import TitanClient
    tc = TitanClient()

    # Fetch all result files published by researchers
    sections = []
    for it in range(1, 10):   # up to 9 iterations (bounded by max_iterations in orchestrator)
        idx = 0
        while True:
            local_path = f"result_{it}_{idx}.txt"
            if not tc.get_artifact(f"research:{run_id}:result:{it}:{idx}", save_path=local_path):
                break
            with open(local_path) as f:
                content = f.read()
            lines    = content.split("\n", 3)
            subtopic = lines[0].replace("SUBTOPIC:", "").strip()
            text     = lines[3].strip() if len(lines) > 3 else content
            sections.append((subtopic, text))
            print(f"[SYNTHESIS]   {subtopic} — {len(text)} chars  ✓", flush=True)
            idx += 1
        # Stop scanning iterations once we hit an empty iteration (no results)
        if idx == 0 and it > 1:
            break

    if not sections:
        print("[ERROR] No research results found.", flush=True)
        sys.exit(1)

    research_block = "\n\n---\n\n".join(
        f"## {name}\n\n{text}" for name, text in sections
    )

    api_key = os.environ.get("GEMINI_API_KEY", "")
    if not api_key:
        print("[ERROR] GEMINI_API_KEY not set.", flush=True)
        sys.exit(1)

    from google import genai
    from google.genai import types

    prompt = f"""You are a senior research analyst writing a final report.

Original query: "{query}"

Research collected by your team:
{research_block}

Write a complete, polished answer to the query using this structure:

# Research Report

## Executive Summary
(3 sentences directly answering the query)

## Key Findings
(5 specific, concrete bullet points — the most important insights)

## Deep Dive
(Integrated narrative weaving together all research sections, ~400 words.
 Connect the findings. Show how they relate to each other.)

## Practical Recommendations
(3-5 actionable takeaways for a team building real systems)

## Open Questions
(2-3 things this research did not resolve — honest gaps)

Format in clean Markdown. Be authoritative and specific."""

    print(f"\n[SYNTHESIS] Calling Gemini for final report...", flush=True)

    client   = genai.Client(api_key=api_key)
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt,
        config=types.GenerateContentConfig(temperature=0.2)
    )

    report = response.text.strip()

    # Write report locally (worker CWD)
    out_filename = f"research_{run_id}_report.md"
    with open(out_filename, "w") as f:
        f.write(f"# Research Report\n\n")
        f.write(f"**Query:** {query}\n\n")
        f.write(f"*Generated by Titan Research Agent · Run ID: `{run_id}`*\n\n---\n\n")
        f.write(report)
        f.write(f"\n\n---\n\n*Sections: {', '.join(s for s, _ in sections)}*\n")

    # Publish report to master — orchestrator retrieves via get_artifact
    try:
        tc.publish_artifact(f"research:{run_id}:report", out_filename)
        tc.store_put(f"research:{run_id}:synth:done", "1")
        print(f"[SYNTHESIS] Report published to master.", flush=True)
    except Exception as e:
        print(f"[SYNTHESIS] TitanStore/upload skipped: {e}", flush=True)

    print(f"\n{'=' * 60}", flush=True)
    for line in report.split("\n"):
        print(line, flush=True)
    print(f"{'=' * 60}\n", flush=True)


if __name__ == "__main__":
    main()
