"""
Generated by Titan Code Generation Agent
Goal: Build a Python CLI task manager with priority queuing and JSON persistence
Run ID: 4b498198d6a4
Components: task_manager, json_persistence, cli_interface
"""

"""
A comprehensive command-line task manager application with priority queuing and JSON persistence.

This program integrates three main components:
1.  **task_manager**: Manages tasks in-memory, including adding, listing, marking complete,
    and retrieving the next highest priority task using a min-heap for efficient priority queuing.
    Tasks are represented by a `Task` class with ID, description, priority, status, and creation timestamp.
2.  **json_persistence**: Handles saving and loading task data to/from a JSON file.
    It provides robust error handling for file operations and JSON parsing.
3.  **cli_interface**: Provides the command-line interface using `argparse`. It orchestrates
    interactions between the user, the `TaskManager`, and the persistence layer,
    displaying task information and processing user commands.

The application allows users to add tasks with priorities, list all tasks (pending or all),
view the next highest priority task, and mark tasks as complete. Task data is automatically
persisted to and loaded from 'tasks.json'.
"""

# --- Standard Library Imports (consolidated) ---
import argparse
import uuid
import heapq
import json
import sys
from datetime import datetime
from typing import List, Dict, Any, Optional, Tuple

# --- Component: task_manager ---
"""
This module implements the core logic for managing tasks, including priority queuing.
It maintains an in-memory collection of tasks and their states. It is agnostic to how
tasks are stored or presented to the user.
"""

# --- Task Model ---

TASK_STATUS_PENDING = "pending"
TASK_STATUS_COMPLETE = "complete"

class Task:
    """
    Represents a single task with its properties.
    Tasks are comparable primarily by priority (lower number = higher priority),
    then by creation date for tie-breaking.
    """
    def __init__(self,
                 description: str,
                 priority: int,
                 task_id: Optional[str] = None,
                 status: str = TASK_STATUS_PENDING,
                 created_at: Optional[str] = None):
        self.id: str = task_id if task_id else str(uuid.uuid4())
        self.description: str = description
        self.priority: int = priority  # Lower number indicates higher priority (e.g., 1 is highest)
        self.status: str = status
        # Store creation time as ISO format string for easy serialization and chronological sorting
        self.created_at: str = created_at if created_at else datetime.now().isoformat()

    def __lt__(self, other: 'Task') -> bool:
        """
        Defines the less-than comparison for Task objects.
        Used for sorting tasks (e.g., in list_tasks) by priority then creation date.
        """
        if self.priority != other.priority:
            return self.priority < other.priority
        # For tasks with the same priority, sort by creation time (older first)
        return self.created_at < other.created_at

    def to_dict(self) -> Dict[str, Any]:
        """Converts the Task object to a dictionary for serialization."""
        return {
            "id": self.id,
            "description": self.description,
            "priority": self.priority,
            "status": self.status,
            "created_at": self.created_at,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'Task':
        """
        Creates a Task object from a dictionary.
        Handles potential missing 'status' field for backward compatibility.
        """
        return cls(
            task_id=data["id"],
            description=data["description"],
            priority=data["priority"],
            status=data.get("status", TASK_STATUS_PENDING), # Default to pending if status is missing
            created_at=data["created_at"],
        )

    def __repr__(self) -> str:
        return (f"Task(id='{self.id[:8]}...', description='{self.description}', "
                f"priority={self.priority}, status='{self.status}', created_at='{self.created_at}')")

# --- Task Manager Core Logic ---

class TaskManager:
    """
    Manages a collection of tasks, including priority queuing and state changes.
    It maintains tasks in-memory and provides methods for adding, retrieving,
    listing, and marking tasks as complete.
    """
    def __init__(self):
        # Stores all tasks (pending and complete) by their ID for quick lookup.
        self._all_tasks: Dict[str, Task] = {}
        # A min-heap for pending tasks. Each element is a tuple:
        # (priority, creation_time_iso_string, task_id).
        # This structure ensures correct ordering:
        # 1. By priority (lowest number first).
        # 2. By creation time (older first) for tasks with the same priority.
        # 3. By task_id (as a tie-breaker, though creation_time should be unique enough).
        # Storing task_id allows retrieval of the Task object from _all_tasks.
        self._pending_tasks_heap: List[Tuple[int, str, str]] = []

    def add_task(self, description: str, priority: int) -> Task:
        """
        Adds a new task to the manager.

        Args:
            description: A brief description of the task.
            priority: An integer representing the task's priority. Lower numbers
                      indicate higher priority (e.g., 1 is highest).

        Returns:
            The newly created Task object.
        """
        new_task = Task(description=description, priority=priority)
        self._all_tasks[new_task.id] = new_task
        
        # Add to the priority queue only if it's a pending task
        if new_task.status == TASK_STATUS_PENDING:
            heapq.heappush(self._pending_tasks_heap, (new_task.priority, new_task.created_at, new_task.id))
        return new_task

    def get_next_task(self) -> Optional[Task]:
        """
        Retrieves the next highest priority pending task.
        Tasks that have been marked complete are skipped (lazy deletion from heap).

        Returns:
            The next highest priority Task object, or None if no pending tasks exist.
        """
        while self._pending_tasks_heap:
            # Pop the task with the highest priority (lowest priority number)
            _, _, task_id = heapq.heappop(self._pending_tasks_heap)
            task = self._all_tasks.get(task_id)

            # Check if the task still exists and is pending.
            # If its status has changed to complete (via mark_complete) or it was
            # removed, it's a "stale" entry in the heap, so we discard it and try the next one.
            if task and task.status == TASK_STATUS_PENDING:
                return task
        return None

    def list_tasks(self, include_completed: bool = False) -> List[Task]:
        """
        Lists tasks, sorted by priority (lowest number first), then by creation date.

        Args:
            include_completed: If True, completed tasks are included in the list.
                               Defaults to False, showing only pending tasks.

        Returns:
            A list of Task objects, sorted as described.
        """
        tasks_to_list = []
        for task in self._all_tasks.values():
            if include_completed or task.status == TASK_STATUS_PENDING:
                tasks_to_list.append(task)
        
        # Sort tasks using the __lt__ method defined in the Task class
        tasks_to_list.sort()
        return tasks_to_list

    def mark_complete(self, task_id: str) -> None:
        """
        Marks a task as complete.

        Args:
            task_id: The unique identifier of the task to mark complete.

        Raises:
            ValueError: If no task with the given ID is found.
        """
        task = self._all_tasks.get(task_id)
        if not task:
            raise ValueError(f"Task with ID '{task_id}' not found.")
        
        task.status = TASK_STATUS_COMPLETE
        # No explicit removal from the heap is needed here.
        # The `get_next_task` method handles "lazy deletion" by skipping completed tasks
        # when they are popped from the heap. This is more efficient than rebuilding the heap.

    def get_all_tasks_data(self) -> List[Dict[str, Any]]:
        """
        Retrieves all tasks (pending and complete) as a list of dictionaries,
        suitable for persistence (e.g., JSON serialization).

        Returns:
            A list of dictionaries, each representing a task.
        """
        return [task.to_dict() for task in self._all_tasks.values()]

    def load_tasks_data(self, tasks_data: List[Dict[str, Any]]) -> None:
        """
        Loads tasks from a list of dictionaries, typically from a persistence layer.
        This clears any existing in-memory tasks and rebuilds the manager's state.

        Args:
            tasks_data: A list of dictionaries, each representing a task.
        """
        # Clear current in-memory state before loading new data
        self._all_tasks.clear()
        self._pending_tasks_heap.clear()

        for data in tasks_data:
            task = Task.from_dict(data)
            self._all_tasks[task.id] = task
            # Rebuild the heap with pending tasks from the loaded data
            if task.status == TASK_STATUS_PENDING:
                heapq.heappush(self._pending_tasks_heap, (task.priority, task.created_at, task.id))


# --- Component: json_persistence ---
"""
This module provides utilities for persisting and loading data to/from JSON files.
It handles serialization and deserialization of generic Python data structures,
specifically lists of dictionaries, which can represent tasks or other entities.
"""

def load_data(filepath: str) -> List[Dict]:
    """
    Loads data from a specified JSON file.

    If the file does not exist, is empty, or contains invalid JSON, an empty list
    is returned, treating these scenarios as an absence of valid data.

    Args:
        filepath (str): The path to the JSON file.

    Returns:
        List[Dict]: A list of dictionaries loaded from the file.
                    Returns an empty list if the file is not found, is empty,
                    or contains invalid JSON.
    """
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            # Attempt to load JSON data from the file
            data = json.load(f)
            # Ensure the loaded data is a list, otherwise return an empty list
            if not isinstance(data, list):
                return []
            return data
    except FileNotFoundError:
        # If the file doesn't exist, there's no data to load, so return an empty list.
        return []
    except json.JSONDecodeError:
        # If the file exists but contains invalid JSON, treat it as no valid data.
        return []
    except Exception as e:
        # Catch any other unexpected errors during file reading (e.g., permission errors)
        print(f"Warning: An unexpected error occurred while loading data from {filepath}: {e}")
        return []

def save_data(filepath: str, data: List[Dict]) -> None:
    """
    Saves a list of dictionaries to a specified JSON file.

    The data is serialized with an indent of 4 spaces for human readability.

    Args:
        filepath (str): The path to the JSON file where data will be saved.
        data (List[Dict]): The list of dictionaries to be saved.
    """
    try:
        with open(filepath, 'w', encoding='utf-8') as f:
            # Serialize the data to JSON format and write it to the file.
            # Using indent=4 makes the JSON file human-readable, which is good for debugging.
            json.dump(data, f, indent=4)
    except IOError as e:
        # Handle potential errors during file writing (e.g., permission errors, disk full)
        print(f"Error: Could not write data to {filepath}: {e}")
    except Exception as e:
        # Catch any other unexpected errors during file writing
        print(f"Warning: An unexpected error occurred while saving data to {filepath}: {e}")


# --- Component: cli_interface ---
"""
This module provides the command-line interface for users to interact with the task manager.
It parses command-line arguments using argparse, orchestrates calls to the 'task_manager'
and 'json_persistence' components, and displays output to the user. It acts as the
application's entry point. Its public interface is primarily a single run() method
that handles the entire CLI lifecycle.
"""

DEFAULT_DATA_FILE = "tasks.json"

class CLIInterface:
    """
    Provides the command-line interface for users to interact with the task manager.
    It parses command-line arguments, orchestrates calls to the 'task_manager'
    and 'json_persistence' components, and displays output to the user.
    """
    def __init__(self,
                 task_manager: TaskManager,
                 load_data_func: callable,
                 save_data_func: callable,
                 data_filepath: str = DEFAULT_DATA_FILE):
        """
        Initializes the CLIInterface with instances of TaskManager and JsonPersistence.

        Args:
            task_manager: An instance of the TaskManager component.
            load_data_func: The function to load data from the persistence layer.
            save_data_func: The function to save data to the persistence layer.
            data_filepath: The path to the JSON file for task persistence.
        """
        self._task_manager = task_manager
        self._load_data_func = load_data_func
        self._save_data_func = save_data_func
        self._data_filepath = data_filepath
        self._parser = self._setup_parser()
        self._load_tasks() # Load tasks on initialization

    def _setup_parser(self) -> argparse.ArgumentParser:
        """
        Configures the argparse ArgumentParser with all supported commands and arguments.
        """
        parser = argparse.ArgumentParser(
            description="A simple command-line task manager with priority queuing."
        )

        subparsers = parser.add_subparsers(dest="command", help="Available commands")

        # Add command
        add_parser = subparsers.add_parser("add", help="Add a new task")
        add_parser.add_argument("description", type=str, help="Description of the task")
        add_parser.add_argument(
            "-p", "--priority", type=int, default=1,
            help="Priority of the task (lower number = higher priority, default: 1)"
        )

        # List command
        list_parser = subparsers.add_parser("list", help="List all tasks")
        list_parser.add_argument(
            "-a", "--all", action="store_true",
            help="Include completed tasks in the list"
        )

        # Next command
        subparsers.add_parser("next", help="Show the next highest priority incomplete task")

        # Complete command
        complete_parser = subparsers.add_parser("complete", help="Mark a task as complete")
        complete_parser.add_argument("task_id", type=str, help="ID of the task to mark complete (first 8 chars usually enough)")

        return parser

    def _load_tasks(self) -> None:
        """
        Loads tasks from the persistence layer into the task manager.
        Handles FileNotFoundError gracefully by starting with an empty task list.
        """
        try:
            tasks_data = self._load_data_func(self._data_filepath)
            self._task_manager.load_tasks_data(tasks_data)
        except Exception as e:
            # Catch broader exceptions during load to prevent CLI from crashing
            print(f"Error loading tasks: {e}. Starting with an empty task list.", file=sys.stderr)
            self._task_manager.load_tasks_data([]) # Ensure manager is in a clean state

    def _save_tasks(self) -> None:
        """Saves current tasks from the task manager to the persistence layer."""
        tasks_data = self._task_manager.get_all_tasks_data()
        self._save_data_func(self._data_filepath, tasks_data)

    def _handle_add(self, args: argparse.Namespace) -> None:
        """Handles the 'add' command."""
        task = self._task_manager.add_task(args.description, args.priority)
        self._save_tasks()
        print(f"Added task: '{task.description}' with priority {task.priority}. ID: {task.id[:8]}...")

    def _handle_list(self, args: argparse.Namespace) -> None:
        """Handles the 'list' command."""
        tasks = self._task_manager.list_tasks(include_completed=args.all)
        if not tasks:
            print("No tasks found.")
            return

        print("Your Tasks:")
        print("-----------")
        for task in tasks:
            status_char = "✓" if task.status == TASK_STATUS_COMPLETE else " "
            print(f"[{status_char}] P{task.priority}: {task.description} (ID: {task.id[:8]}...)")
        print("-----------")

    def _handle_next(self, args: argparse.Namespace) -> None:
        """Handles the 'next' command."""
        task = self._task_manager.get_next_task()
        if task:
            print("Next task:")
            print(f"P{task.priority}: {task.description} (ID: {task.id[:8]}...)")
        else:
            print("No incomplete tasks available. Time for a break!")

    def _handle_complete(self, args: argparse.Namespace) -> None:
        """Handles the 'complete' command."""
        all_tasks = self._task_manager.list_tasks(include_completed=True)
        matching_tasks = [t for t in all_tasks if t.id.startswith(args.task_id)]

        if not matching_tasks:
            print(f"Error: No task found with ID starting with '{args.task_id}'.", file=sys.stderr)
            return
        if len(matching_tasks) > 1:
            print(f"Error: Multiple tasks found matching '{args.task_id}'. Please provide a more specific ID.", file=sys.stderr)
            for task in matching_tasks:
                print(f"  - {task.id[:8]}...: {task.description}", file=sys.stderr)
            return

        try:
            self._task_manager.mark_complete(matching_tasks[0].id)
            self._save_tasks()
            print(f"Task '{matching_tasks[0].description}' (ID: {matching_tasks[0].id[:8]}...) marked as complete.")
        except ValueError as e:
            print(f"Error: {e}", file=sys.stderr)
        except Exception as e:
            print(f"An unexpected error occurred: {e}", file=sys.stderr)

    def run(self, argv: Optional[List[str]] = None) -> None:
        """
        The main entry point for the CLI.
        Parses arguments, dispatches commands, and handles output.

        Args:
            argv: Optional list of arguments to parse (defaults to sys.argv[1:]).
                  Useful for testing.
        """
        args = self._parser.parse_args(argv)

        if not hasattr(args, 'command') or args.command is None:
            self._parser.print_help()
            return

        if args.command == "add":
            self._handle_add(args)
        elif args.command == "list":
            self._handle_list(args)
        elif args.command == "next":
            self._handle_next(args)
        elif args.command == "complete":
            self._handle_complete(args)
        else:
            print(f"Unknown command: {args.command}", file=sys.stderr)
            self._parser.print_help(sys.stderr)

# --- Main Application Entry Point ---

def main():
    """
    Main function to set up and run the CLI task manager application.
    """
    task_manager_instance = TaskManager()
    
    cli = CLIInterface(
        task_manager=task_manager_instance,
        load_data_func=load_data,
        save_data_func=save_data
    )
    cli.run()

if __name__ == "__main__":
    main()